// Route definitions
export const ROUTES = {
  home: '/',
  rideBooking: '/ride-booking',
  rideTracking: '/ride-tracking',
  rideHistory: '/ride-history',
  profile: '/profile',
  rating: '/rating',
  help: '/help',
  login: '/login',
  register: '/register',
  otpVerification: '/otp-verification',
  riderDashboard: '/rider/dashboard',
  riderAcceptRide: '/rider/accept-ride',
  riderRideHistory: '/rider/ride-history',
  riderProfile: '/rider/profile',
  riderHelp: '/rider/help',
  adminDashboard: '/admin/dashboard',
  adminUserManagement: '/admin/user-management',
  adminRideManagement: '/admin/ride-management',
  adminReports: '/admin/reports',
  adminRatingsReview: '/admin/ratings-review',
  adminHelpManagement: '/admin/help-management',
  notFound: '*',
};
